### ISSUE TITLE
For porting to other OS:Amoebaの他OSへの移植について

### ISSUE THREAD

**Issue by penus** [Alliance-Network/Amoeba#1]
Many users wanted a porting to other OS.
多くのユーザーは、他のOSへの移植を望んでいます。
Typical OS is Linux,BSD,MacOSX.
代表的なOSはLinux、BSD、MacOSXです。
It is possible to match the BSD, you can respond to Linux and MacOSX.
BSDに合わせることで、LinuxとMacOSXに対応できます。

**Comment by Lyrise** [comment]
Your wishes will when the developer shortage and the funds shortage have been resolved come true.
人手不足と資金不足が解決した時、あなたの願いはかなえられるでしょう。
