### ISSUE TITLE
Can't share anything

### ISSUE THREAD

**Issue by marcosteam** [Alliance-Network/Amoeba#8]
I still have some free space,about 20GB.
But I can't share anything.It always display "syncing" and it takes a lot of space.But it dosen't make progress.
Until it says "Not enough disk space."
And it will stop connecting.I have to restart it.
The error log:
2017/11/04 22:39:16 Warning:	Exception:	Newtonsoft.Json.JsonSerializationException
Message:	Unable to find a constructor to use for type System.Collections.Immutable.ImmutableDictionary`2[System.String,System.Collections.Immutable.ImmutableHashSet`1[System.String]]. Path 'Map', line 1, position 586.
StackTrace:
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(JsonReader reader, JsonArrayContract contract, Boolean& createdFromNonDefaultCreator)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   在 Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   在 Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   在 Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   在 Omnius.Configuration.Settings.Load[T](String directoryPath, String name, Func`1 defaultValueFactory)

**Comment by AllianceNetPR** [comment]
The problem that Amoeba gives an error message "Not enough disk space." even though you have enough free disk space is due to the reduced free space in the cache. You can solve by increasing the cache size in the option to be 3 times larger than the size that you used for the download and upload.

**Comment by AllianceNetPR** [comment]
@marcosteam 
We fixed the problems. Please download the latest Amoeba.
https://github.com/Alliance-Network/Amoeba/releases

Thank you for your issues.
